services:
  postgres-demo:
    image: postgres:17-alpine
    container_name: postgres17-demo-data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_demo_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U postgres -d demo -tAc \"SELECT 1 FROM public.airplanes_marts LIMIT 1\" | grep -q 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 60s

  postgres-mart:
    image: postgres:17-alpine
    container_name: postgres17-mart
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mart
    ports:
      - "5433:5432"
    volumes:
      - postgres_mart_data:/var/lib/postgresql/data
    restart: unless-stopped
    depends_on:
      postgres-demo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mart"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_demo_data:
  postgres_mart_data:
